# Generated by Django 4.0.8 on 2023-10-19 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_bangla', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('description_bangla', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_inventory_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'm_inventory_type',
            },
        ),
        migrations.CreateModel(
            name='RemainingInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentory_expense_remaining.masterinventory')),
            ],
            options={
                'verbose_name': 'Remaining Inventory',
                'verbose_name_plural': 'Remaining Inventories',
                'db_table': 'remaining_inventory',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_or_remove', models.CharField(max_length=10)),
                ('total_crops', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('crop_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentory_expense_remaining.masterinventory')),
            ],
            options={
                'db_table': 'innnvventory',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shed_supply', models.CharField(default='Shed 1', max_length=100)),
                ('quantity_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentory_expense_remaining.inventory')),
            ],
        ),
    ]
