# Generated by Django 4.0.8 on 2023-10-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100, unique=True)),
                ('crop_price_per_kg', models.DecimalField(decimal_places=4, max_digits=10)),
                ('crop_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RemainingCrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_remaining', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentory_expense_remaining.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shed_supply', models.CharField(default='Shed 1', max_length=100)),
                ('quantity_sold', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incentory_expense_remaining.inventory')),
            ],
        ),
    ]
