# Generated by Django 4.0.8 on 2023-10-23 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incentory_expense_remaining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
