# Generated by Django 4.0.8 on 2023-10-15 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shed_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shedName', models.CharField(max_length=100)),
                ('shedLength', models.FloatField(default=0.0)),
                ('shedWidth', models.FloatField(default=0.0)),
                ('shedLocation', models.TextField(max_length=300)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_cow', models.IntegerField(default=0)),
                ('pcow', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
