# Generated by Django 4.2.5 on 2023-10-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shed_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shedName', models.CharField(max_length=100)),
                ('shedLength', models.FloatField(default=0.0)),
                ('shedWidth', models.FloatField(default=0.0)),
                ('shedLocation', models.TextField(max_length=300)),
                ('phoneNumber', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('number_of_cow', models.IntegerField(default=0)),
            ],
        ),
    ]
