# Generated by Django 4.2.5 on 2023-10-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shed_registration',
            name='phoneNumber',
            field=models.CharField(max_length=11),
        ),
    ]
