# Generated by Django 4.0.8 on 2023-10-15 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shed_registration',
            name='pcow',
        ),
        migrations.AlterField(
            model_name='shed_registration',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
