# Generated by Django 4.2.5 on 2023-10-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shed', '0002_alter_shed_registration_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shed_registration',
            name='shedLength',
        ),
    ]
