# Generated by Django 4.0.8 on 2023-10-15 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shed', '0002_remove_shed_registration_pcow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shed_registration',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheds', to=settings.AUTH_USER_MODEL),
        ),
    ]
