# Generated by Django 4.2.5 on 2023-10-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shed', '0003_remove_shed_registration_shedlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='shed_registration',
            name='shedLength',
            field=models.FloatField(default=0.0),
        ),
    ]
