# Generated by Django 4.0.8 on 2023-10-19 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CowRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattle_id', models.CharField(max_length=10, unique=True)),
                ('origin', models.CharField(choices=[('Local', 'Local'), ('Imported', 'Imported')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('color', models.CharField(max_length=50)),
                ('breeding_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('milk_yield', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
        ),
        migrations.CreateModel(
            name='MasterDesease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desease_name', models.CharField(max_length=100)),
                ('desease_description', models.TextField()),
                ('desease_description_bangla', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_desease_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'm_desease',
            },
        ),
        migrations.CreateModel(
            name='MilkYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('milk_produced', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_yields', to='cow.cowregistration')),
            ],
        ),
        migrations.CreateModel(
            name='MasterVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('vaccine_details', models.TextField()),
                ('vaccine_details_bangla', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('desease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cow.masterdesease')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_mastervaccine_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'm_vaccine',
            },
        ),
        migrations.CreateModel(
            name='MasterMedicin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_details', models.TextField()),
                ('medicine_details_bangla', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('desease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cow.masterdesease')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_mastermedicine_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'm_medicine',
            },
        ),
        migrations.AddField(
            model_name='cowregistration',
            name='desease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CowDesease', to='cow.masterdesease'),
        ),
        migrations.AddField(
            model_name='cowregistration',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CowMedicine', to='cow.mastermedicin'),
        ),
        migrations.AddField(
            model_name='cowregistration',
            name='shed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CowRegistration', to='shed.shed_registration'),
        ),
        migrations.AddField(
            model_name='cowregistration',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CowVaccine', to='cow.mastervaccine'),
        ),
    ]
