# Generated by Django 4.0.8 on 2023-10-17 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shed', '0003_alter_shed_registration_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattle_id', models.CharField(max_length=10, unique=True)),
                ('origin', models.CharField(choices=[('Local', 'Local'), ('Imported', 'Imported')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('color', models.CharField(max_length=50)),
                ('breeding_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('milk_yield', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('shed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CowRegistration', to='shed.shed_registration')),
            ],
        ),
        migrations.CreateModel(
            name='MilkYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('milk_produced', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_yields', to='cow.cowregistration')),
            ],
        ),
    ]
