# Generated by Django 4.0.8 on 2023-10-22 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowregistration',
            name='current_vaccine_dose',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3')], decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='cowregistration',
            name='helth_status',
            field=models.CharField(choices=[('Good', 'Good'), ('Sick', 'Sick'), ('Natural', 'Natural')], default='Natural', max_length=30),
        ),
        migrations.AddField(
            model_name='cowregistration',
            name='next_vaccine_dose',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Sick_Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_desease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SickCowDesease', to='cow.masterdesease')),
                ('cow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SeickCowID', to='cow.cowregistration')),
            ],
        ),
    ]
