# Generated by Django 4.0.8 on 2023-10-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0002_cowregistration_current_vaccine_dose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowregistration',
            name='current_vaccine_dose',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3')], decimal_places=2, default=2, max_digits=4),
        ),
    ]
