# Generated by Django 4.0.8 on 2023-10-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0004_alter_cowregistration_current_vaccine_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowregistration',
            name='current_vaccine_dose',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
