# Generated by Django 4.0.8 on 2023-10-22 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0006_alter_cowregistration_current_vaccine_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sick_cow',
            name='cow_desease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SickCowDesease', to='cow.masterdesease'),
        ),
        migrations.AlterField(
            model_name='sick_cow',
            name='cow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SeickCowID', to='cow.cowregistration'),
        ),
    ]
