# Generated by Django 4.0.8 on 2023-10-30 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0009_alter_cowregistration_desease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowregistration',
            name='delivery_status',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='desease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CowDesease', to='cow.masterdesease'),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='heat_status',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='helth_status',
            field=models.CharField(choices=[('Good', 'Good'), ('Sick', 'Sick'), ('Natural', 'Natural')], default='Natural', max_length=30),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CowMedicine', to='cow.mastermedicin'),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='semen_push_status',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CowVaccine', to='cow.mastervaccine'),
        ),
    ]
