# Generated by Django 4.0.8 on 2023-10-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0010_alter_cowregistration_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowregistration',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
