# Generated by Django 4.0.8 on 2023-10-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0011_alter_cowregistration_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowregistration',
            name='origin',
            field=models.CharField(max_length=10),
        ),
    ]
