# Generated by Django 4.0.8 on 2023-10-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0012_alter_cowregistration_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cowregistration',
            name='desease',
        ),
        migrations.AddField(
            model_name='cowregistration',
            name='desease',
            field=models.ManyToManyField(blank=True, related_name='CowDesease', to='cow.masterdesease'),
        ),
        migrations.RemoveField(
            model_name='cowregistration',
            name='medicine',
        ),
        migrations.AddField(
            model_name='cowregistration',
            name='medicine',
            field=models.ManyToManyField(null=True, related_name='CowMedicine', to='cow.mastermedicin'),
        ),
        migrations.RemoveField(
            model_name='cowregistration',
            name='vaccine',
        ),
        migrations.AddField(
            model_name='cowregistration',
            name='vaccine',
            field=models.ManyToManyField(null=True, related_name='CowVaccine', to='cow.mastervaccine'),
        ),
    ]
