# Generated by Django 4.0.8 on 2023-11-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0013_remove_cowregistration_desease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowregistration',
            name='helth_status',
            field=models.CharField(default='Natural', max_length=30),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='medicine',
            field=models.ManyToManyField(blank=True, related_name='CowMedicine', to='cow.mastermedicin'),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='vaccine',
            field=models.ManyToManyField(blank=True, related_name='CowVaccine', to='cow.mastervaccine'),
        ),
    ]
