# Generated by Django 4.0.8 on 2023-11-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0014_alter_cowregistration_helth_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowregistration',
            name='delivery_status',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='heat_status',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='semen_push_status',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
