# Generated by Django 4.0.8 on 2023-11-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0016_cowregistration_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
