# Generated by Django 4.0.8 on 2023-11-01 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0017_alter_cowregistration_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowregistration',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
