# Generated by Django 4.0.8 on 2023-11-02 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0019_alter_cowregistration_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowregistration',
            name='cattle_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='next_vaccine_dose',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cowregistration',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
