# Generated by Django 4.0.8 on 2023-11-02 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0020_alter_cowregistration_cattle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowregistration',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
