# Generated by Django 4.0.8 on 2023-11-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0021_alter_cowregistration_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowregistration',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
    ]
