# Generated by Django 4.0.8 on 2023-11-02 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0022_alter_cowregistration_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sick_cow',
            name='cow_desease',
        ),
        migrations.AddField(
            model_name='sick_cow',
            name='cow_desease',
            field=models.ManyToManyField(blank=True, related_name='SickCowDesease', to='cow.masterdesease'),
        ),
        migrations.AlterField(
            model_name='sick_cow',
            name='cow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SeickCowID', to='cow.cowregistration'),
        ),
    ]
