# Generated by Django 4.0.8 on 2023-11-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0023_remove_sick_cow_cow_desease_sick_cow_cow_desease_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sick_cow',
            table='sick_table',
        ),
    ]
