# Generated by Django 4.0.8 on 2023-11-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0024_alter_sick_cow_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sick_cow',
            name='cow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SeickCowID', to='cow.cowregistration'),
        ),
    ]
