# Generated by Django 4.0.8 on 2023-11-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0027_alter_cowregistration_purchase_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='milkyield',
            table='milk_table',
        ),
    ]
