# Generated by Django 4.0.8 on 2023-11-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0028_alter_milkyield_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkyield',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
