# Generated by Django 4.0.8 on 2023-11-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cow', '0029_alter_milkyield_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='milkyield',
            unique_together={('date', 'cow')},
        ),
    ]
